# Default parameters, even this default build is excluded in the build
# matrix below. We define so Travis doesn't think this is a Ruby
# project.
os: linux
dist: focal
language: c
compiler: gcc

# Define the default CFLAGS used by all builds as a YAML anchor.
default-cflags: &default-cflags
   CFLAGS="-Wall -Wno-unused-parameter -Wno-unused-function"
   #CFLAGS="-Wall -Wextra -Werror -Wno-unused-parameter -Wno-unused-function"

# The default build is Linux with gcc. Add additional builds to the
# matrix here.
matrix:
  # Exclude the default build so any the builds in the matrix will be done.
  exclude:
    - os: linux
      compiler: gcc
  include:
    # Linux, gcc, tests enabled.
    - os: linux
      compiler: gcc
      env:
        - NAME="linux,gcc"
        - *default-cflags
    # Linux, clang. For this build we'll also enable -Wshadow.
    - os: linux
      compiler: clang
      env:
        - NAME="linux,clang"
        - *default-cflags
        - EXTRA_CFLAGS="-Wshadow"

# Change this to your needs
script:
  - ./autogen.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ./configure || { echo "!!!! ERROR !!!!"; cat config.log && false; }
    fi
  - make
  - cd tools
  - make

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        sudo apt-get update -qq
        sudo apt-get install -y libpcre3-dev liblognorm-dev \
            build-essential autoconf automake libyaml-dev \
            pkg-config libhiredis-dev libfastjson-dev

    fi

